[package]
name = "unix_shell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = { version = "0.27.1", features = ["fs", "process"] }
rustyline = "13.0.0"
tempfile = "3.8.1"
